---
title: "gReatmigRation"
author: "Sean Kiah, Baylie Larsen, Blake Prall, Hannah Sutoris"
date: "2023-11-30"
output: html_document
---

##Introduction


##Methods


##Results


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rgbif)
library(tidyverse)
library(MuMIn)
library(rnoaa)
library(data.table)
library(ggmap)
library(usmap)
library(magick)
library(cowplot)
library(lme4)
library(car)
library(sf)
library(knitr)
library(kableExtra)
```

(the 5 birds i chose at random)
Blue-winged Warbler
Baltimore Oriole
Great Crested Flycatcher
Olive-sided Flycatcher
Black-billed Cuckoo

```{r, echo=FALSE, cache=TRUE}
species <- c("Icterus galbula", "Vermivora cyanoptera", "Myiarchus crinitus", "Contopus cooperi", "Coccyzus erythropthalmus")
y <- paste0("2000",",","2019")
m <- paste0("4",",","5")
dat.l <-list()

for(s in species){

n.obs <-  occ_data(scientificName = s,year=y,month=m,limit=0,country="US",basisOfRecord = "HUMAN_OBSERVATION",stateProvince="Massachusetts")$meta$count 

print(n.obs)


dat.l[[paste0(s)]] <- occ_data(scientificName = s,year=y,month=m,
                               limit=n.obs,country="US",
                               basisOfRecord = "HUMAN_OBSERVATION",
                               stateProvince="Massachusetts")[[2]]


}

dat <- rbindlist(dat.l,fill=T)

head(dat)
```



```{r, echo=FALSE}
saveRDS(data,"massbird.data.RDS")

dat%>%
  group_by(year,species)%>%
  summarise(count=sum(individualCount,na.rm = T))%>%
  ggplot(aes(x=year,y=count,col=species))+geom_point()

options(noaakey = "GemgcypRGxXkwpqKtKzsVrRwZhuSpzka")

sts <- c(
  "GHCND:USW00013894", #Mobible, AL 2k away about 10 days away @200 km/day
  "GHCND:USW00013881", #Charlotte, NC 1000 km away about 6 days away @200 km/day
  "GHCND:USW00014739" #Boston
)

bos <- ncdc_stations(stationid = "GHCND:USW00014739")
print(bos)

sta.d <- bind_rows(
  lapply(sts,function(x) ncdc_stations(stationid = x)$data ) 
  )%>%
  mutate(usmap_transform(.,input_names = c("longitude","latitude"),output_names = c("longitude.1", "latitude.1")))%>% 
  mutate(name=str_sub(name, -5,-4))%>%
  mutate(migr.day=c(10,5,0))%>% 
  separate(id,into = c("station.type","id"))%>%
        print()

plot_usmap(
  include = c(.northeast_region,.south_region,.east_north_central)
)+geom_point(data=sta.d,aes(x=longitude.1,y=latitude.1,col=name),size=5)+geom_label(data=sta.d,aes(x=longitude.1,y=latitude.1,col=name,label=name),size=5,nudge_x = 1e6*0.25)+theme(legend.position = "none")

weather.d <- meteo_pull_monitors(sta.d$id,date_min = "2000-01-01")
head(weather.d)

```

```{r, echo=FALSE}
#for Icterus galbula
ig<- dat%>%
  filter(species=="Icterus galbula")%>%
  group_by(year)%>%
  mutate(date=as.Date(paste0(year,"-",month,"-",day)),
         j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01")))
  )%>%
  group_by(species,year,j.day,date)%>%
  summarise(day.tot=sum(individualCount,na.rm=T))%>%
  group_by(species,year)%>%
  mutate(prop=cumsum(day.tot/sum(day.tot,na.rm = T)))
         
ig%>%
  ggplot(aes(j.day,prop))+geom_point()+facet_wrap(year~.)
ig.pred <- mc%>%
  group_by(year)%>%
 summarize(
   pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),
   j.day=min(j.day):max(j.day),
  )%>%
  left_join(mc%>%dplyr::select(j.day,date))

ig%>%
  ggplot(aes(j.day,prop))+geom_point(aes=0.3)+geom_line(data=mc.pred,aes(x=j.day,y=pred),col="blue",size=2)+facet_wrap(year~.)

ig.arrive.date <-ig.pred%>%
  group_by(year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])

ig.arrive.date%>%
  ggplot(aes(year,j.day))+geom_point()

```
```{r, echo=FALSE}
#for Vermivora cyanoptera
vc<- dat%>%
  filter(species=="Vermivora cyanoptera")%>%
  group_by(year)%>%
  mutate(date=as.Date(paste0(year,"-",month,"-",day)),
         j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01")))
  )%>%
  group_by(species,year,j.day,date)%>%
  summarise(day.tot=sum(individualCount,na.rm=T))%>%
  group_by(species,year)%>%
  mutate(prop=cumsum(day.tot/sum(day.tot,na.rm = T)))
         
vc%>%
  ggplot(aes(j.day,prop))+geom_point()+facet_wrap(year~.)
vc.pred <- vc%>%
  group_by(year)%>%
 summarize(
   pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),
   j.day=min(j.day):max(j.day),
  )%>%
  left_join(mc%>%dplyr::select(j.day,date))

vc%>%
  ggplot(aes(j.day,prop))+geom_point(aes=0.3)+geom_line(data=mc.pred,aes(x=j.day,y=pred),col="blue",size=2)+facet_wrap(year~.)

vc.arrive.date <-vc.pred%>%
  group_by(year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])

vc.arrive.date%>%
  ggplot(aes(year,j.day))+geom_point()

```
```{r, echo=FALSE}
#for Myiarchus crinitus
mc<- dat%>%
  filter(species=="Myiarchus crinitus")%>%
  group_by(year)%>%
  mutate(date=as.Date(paste0(year,"-",month,"-",day)),
         j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01")))
  )%>%
  group_by(species,year,j.day,date)%>%
  summarise(day.tot=sum(individualCount,na.rm=T))%>%
  group_by(species,year)%>%
  mutate(prop=cumsum(day.tot/sum(day.tot,na.rm = T)))
         
mc%>%
  ggplot(aes(j.day,prop))+geom_point()+facet_wrap(year~.)
mc.pred <- mc%>%
  group_by(year)%>%
 summarize(
   pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),
   j.day=min(j.day):max(j.day),
  )%>%
  left_join(mc%>%dplyr::select(j.day,date))

mc%>%
  ggplot(aes(j.day,prop))+geom_point(aes=0.3)+geom_line(data=mc.pred,aes(x=j.day,y=pred),col="blue",size=2)+facet_wrap(year~.)

mc.arrive.date <-mc.pred%>%
  group_by(year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])

mc.arrive.date%>%
  ggplot(aes(year,j.day))+geom_point()

```

```{r, echo=FALSE}
#for Contopus cooperi
cc<- dat%>%
  filter(species=="Contopus cooperi")%>%
  group_by(year)%>%
  mutate(date=as.Date(paste0(year,"-",month,"-",day)),
         j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01")))
  )%>%
  group_by(species,year,j.day,date)%>%
  summarise(day.tot=sum(individualCount,na.rm=T))%>%
  group_by(species,year)%>%
  mutate(prop=cumsum(day.tot/sum(day.tot,na.rm = T)))
         
cc%>%
  ggplot(aes(j.day,prop))+geom_point()+facet_wrap(year~.)
cc.pred <- cc%>%
  group_by(year)%>%
 summarize(
   pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),
   j.day=min(j.day):max(j.day),
  )%>%
  left_join(mc%>%dplyr::select(j.day,date))

cc%>%
  ggplot(aes(j.day,prop))+geom_point(aes=0.3)+geom_line(data=mc.pred,aes(x=j.day,y=pred),col="blue",size=2)+facet_wrap(year~.)

cc.arrive.date <-cc.pred%>%
  group_by(year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])

cc.arrive.date%>%
  ggplot(aes(year,j.day))+geom_point()

```

```{r, echo=FALSE}
#for Coccyzus erythropthalmus
ce<- dat%>%
  filter(species=="Coccyzus erythropthalmus")%>%
  group_by(year)%>%
  mutate(date=as.Date(paste0(year,"-",month,"-",day)),
         j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01")))
  )%>%
  group_by(species,year,j.day,date)%>%
  summarise(day.tot=sum(individualCount,na.rm=T))%>%
  group_by(species,year)%>%
  mutate(prop=cumsum(day.tot/sum(day.tot,na.rm = T)))
         
ce%>%
  ggplot(aes(j.day,prop))+geom_point()+facet_wrap(year~.)
ce.pred <- ce%>%
  group_by(year)%>%
 summarize(
   pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),
   j.day=min(j.day):max(j.day),
  )%>%
  left_join(mc%>%dplyr::select(j.day,date))

ce%>%
  ggplot(aes(j.day,prop))+geom_point(aes=0.3)+geom_line(data=mc.pred,aes(x=j.day,y=pred),col="blue",size=2)+facet_wrap(year~.)

ce.arrive.date <-ce.pred%>%
  group_by(year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])

ce.arrive.date%>%
  ggplot(aes(year,j.day))+geom_point()
```


```{r, echo=FALSE}
weather.d <- weather.d%>%
  mutate(year=as.integer(str_sub(date,1,4)), 
         date=as.Date(date))%>%
  group_by(year)%>% 
 mutate(j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01"))), 
  date2=date,
  wdir.rad=(180-abs(wdf2-180))*pi/180, 
  wvec=cos(wdir.rad)*-1*awnd 
  )%>% 
  dplyr::select(id,year,date2,j.day,tmin,tmax,wvec)%>% 
  left_join(sta.d%>%select(id,name,migr.day))%>% 
  mutate(j.day=j.day+migr.day)

```
```{r, echo=FALSE}
#mean arrival time for Icterus galbula
ig.arr.weath <- ig.arrive.date%>%
  left_join(weather.d)%>%
  left_join(mc%>%dplyr::select(year,date,j.day))
head(ig.arr.weath)

weather.wk <-weather.d %>% 
  group_by(year,name) %>% 
  mutate(wk.tmin = frollmean(tmin, n=14,align="right"),
         wk.tmax = frollmean(tmax, n=14,align="right"),
         wk.wvec = frollmean(wvec, n=14,align="right")
         )%>%
  dplyr::select(j.day,date2,name,wk.tmin,wk.tmax,wk.wvec)

ig.arr.weath2 <- ig.arrive.date%>%
  left_join(weather.wk)
head(ig.arr.weath2)
```
```{r, echo=FALSE}
#mean arrival time for Vermivora cyanoptera
vc.arr.weath <- vc.arrive.date%>%
  left_join(weather.d)%>%
  left_join(mc%>%dplyr::select(year,date,j.day))
head(vc.arr.weath)

weather.wk <-weather.d %>% 
  group_by(year,name) %>% 
  mutate(wk.tmin = frollmean(tmin, n=14,align="right"),
         wk.tmax = frollmean(tmax, n=14,align="right"),
         wk.wvec = frollmean(wvec, n=14,align="right")
         )%>%
  dplyr::select(j.day,date2,name,wk.tmin,wk.tmax,wk.wvec)

vc.arr.weath2 <- vc.arrive.date%>%
  left_join(weather.wk)
head(vc.arr.weath2)
```
```{r, echo=FALSE}
#mean arrival time for Myiarchus crinitus
mc.arr.weath <- mc.arrive.date%>%
  left_join(weather.d)%>%
  left_join(mc%>%dplyr::select(year,date,j.day))
head(mc.arr.weath)

weather.wk <-weather.d %>% 
  group_by(year,name) %>% 
  mutate(wk.tmin = frollmean(tmin, n=14,align="right"),
         wk.tmax = frollmean(tmax, n=14,align="right"),
         wk.wvec = frollmean(wvec, n=14,align="right")
         )%>%
  dplyr::select(j.day,date2,name,wk.tmin,wk.tmax,wk.wvec)

mc.arr.weath2 <- mc.arrive.date%>%
  left_join(weather.wk)
head(mc.arr.weath2)
```
```{r, echo=FALSE}
#mean arrival time for Contopus cooperi
cc.arr.weath <- cc.arrive.date%>%
  left_join(weather.d)%>%
  left_join(cc%>%dplyr::select(year,date,j.day))
head(cc.arr.weath)

weather.wk <-weather.d %>% 
  group_by(year,name) %>% 
  mutate(wk.tmin = frollmean(tmin, n=14,align="right"),
         wk.tmax = frollmean(tmax, n=14,align="right"),
         wk.wvec = frollmean(wvec, n=14,align="right")
         )%>%
  dplyr::select(j.day,date2,name,wk.tmin,wk.tmax,wk.wvec)

cc.arr.weath2 <- cc.arrive.date%>%
  left_join(weather.wk)
head(cc.arr.weath2)
```

```{r, echo=FALSE}
#mean arrival time for Coccyzus erythropthalmus
ce.arr.weath <- ce.arrive.date%>%
  left_join(weather.d)%>%
  left_join(ce%>%dplyr::select(year,date,j.day))
head(ce.arr.weath)

weather.wk <-weather.d %>% 
  group_by(year,name) %>% 
  mutate(wk.tmin = frollmean(tmin, n=14,align="right"),
         wk.tmax = frollmean(tmax, n=14,align="right"),
         wk.wvec = frollmean(wvec, n=14,align="right")
         )%>%
  dplyr::select(j.day,date2,name,wk.tmin,wk.tmax,wk.wvec)

ce.arr.weath2 <- ce.arrive.date%>%
  left_join(weather.wk)
head(ce.arr.weath2)
```


```{r, echo=FALSE}
#linear mixed effect for Icterus galbula
ig.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),ig.arr.weath,na.action = "na.fail")
Anova(ig.lmer)

ig.lmer2 <- lmer(j.day~wk.tmin*wk.tmax*wk.wvec+(1|name),ig.arr.weath2,na.action = "na.fail")
Anova(ig.lmer2)

ig.arr.aic <- dredge(ig.lmer2,fixed = c("wk.tmin","wk.tmax","wk.wvec"),)
ig.kb <- kable(ig.arr.aic[1:4,],caption = "Fit values for nested models of the most complicated lme model")
kable_styling(ig.kb)

best.lmer <-  lmer(j.day~wk.tmin+wk.tmax+wk.wvec+(1|name),ig.arr.weath2,na.action = "na.fail")
Anova(best.lmer)
```

```{r, echo=FALSE}
#linear mixed effect for Vermivora cyanoptera
vc.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),vc.arr.weath,na.action = "na.fail")
Anova(vc.lmer)

vc.lmer2 <- lmer(j.day~wk.tmin*wk.tmax*wk.wvec+(1|name),vc.arr.weath2,na.action = "na.fail")
Anova(vc.lmer2)

vc.arr.aic <- dredge(vc.lmer2,fixed = c("wk.tmin","wk.tmax","wk.wvec"),)
vc.kb <- kable(vc.arr.aic[1:4,],caption = "Fit values for nested models of the most complicated lme model")
kable_styling(vc.kb)

best.lmer <-  lmer(j.day~wk.tmin+wk.tmax+wk.wvec+(1|name),vc.arr.weath2,na.action = "na.fail")
Anova(best.lmer)
```

```{r, echo=FALSE}
#linear mixed effect for Myiarchus crinitus
mc.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),mc.arr.weath,na.action = "na.fail")
Anova(mc.lmer)

mc.lmer2 <- lmer(j.day~wk.tmin*wk.tmax*wk.wvec+(1|name),mc.arr.weath2,na.action = "na.fail")
Anova(mc.lmer2)

mc.arr.aic <- dredge(mc.lmer2,fixed = c("wk.tmin","wk.tmax","wk.wvec"),)
mc.kb <- kable(mc.arr.aic[1:4,],caption = "Fit values for nested models of the most complicated lme model")
kable_styling(mc.kb)

best.lmer <-  lmer(j.day~wk.tmin+wk.tmax+wk.wvec+(1|name),mc.arr.weath2,na.action = "na.fail")
Anova(best.lmer)
```

```{r, echo=FALSE}
#linear mixed effect for Contopus cooperi
cc.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),cc.arr.weath,na.action = "na.fail")
Anova(cc.lmer)

cc.lmer2 <- lmer(j.day~wk.tmin*wk.tmax*wk.wvec+(1|name),cc.arr.weath2,na.action = "na.fail")
Anova(cc.lmer2)

cc.arr.aic <- dredge(cc.lmer2,fixed = c("wk.tmin","wk.tmax","wk.wvec"),)
cc.kb <- kable(cc.arr.aic[1:4,],caption = "Fit values for nested models of the most complicated lme model")
kable_styling(cc.kb)

best.lmer <-  lmer(j.day~wk.tmin+wk.tmax+wk.wvec+(1|name),cc.arr.weath2,na.action = "na.fail")
Anova(best.lmer)
```

```{r, echo=FALSE}
#linear mixed effect for Coccyzus erythropthalmus
ce.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),ce.arr.weath,na.action = "na.fail")
Anova(ce.lmer)

ce.lmer2 <- lmer(j.day~wk.tmin*wk.tmax*wk.wvec+(1|name),ce.arr.weath2,na.action = "na.fail")
Anova(ce.lmer2)

ce.arr.aic <- dredge(ce.lmer2,fixed = c("wk.tmin","wk.tmax","wk.wvec"),)
ce.kb <- kable(ce.arr.aic[1:4,],caption = "Fit values for nested models of the most complicated lme model")
kable_styling(ce.kb)

best.lmer <-  lmer(j.day~wk.tmin+wk.tmax+wk.wvec+(1|name),ce.arr.weath2,na.action = "na.fail")
Anova(best.lmer)
```

##Discussion


##Author Contributions
Sean-
Hannah-
Blake-
Baylie-

##References
